name: Deploy to Local Network

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted  

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Git Pull on Local Server
      run: |
        cd /home/Bastian/weight_tracker && git pull origin main
